// @ts-check
import { defineConfig } from "astro/config";

// Site URL is canonical for sitemap.xml + RSS feed + Open Graph tags.
// Repointing the affiliate site to a different domain is a one-line
// change here + DNS update in the registrar.
//
// Sitemap is generated by `src/pages/sitemap.xml.ts` (manual route)
// rather than @astrojs/sitemap — the integration has a known bug with
// empty content collections in Astro 4.x. Manual route is bulletproof
// and gives us identical output.
export default defineConfig({
  site: "https://settled.world",
  trailingSlash: "ignore",
  build: {
    // Static-only output — Vercel just serves the built files.
    format: "directory",
  },
});
